version: "3"
services:
  react-app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:9000"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
